const shopActionTypes = {
    FETCH_COLLECTION_START:"FETCH_COLLECTION_START",
    FETCH_COLLECTION_SUCCES:"FETCH_COLLECTION_SUCCES",
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_SUCCESFETCH_COLLECTION_SUCCES'
}

export default shopActionTypes;